services:
  nginx:
    build:
      context: ./App/docker
      dockerfile: nginx.docker
    volumes:
      - ./App:/app
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_PORT}:80
  php-fpm:
    build:
      context: ./App/docker
      dockerfile: php-fpm.docker
    volumes:
      - ./App:/app
  php-cli:
    build:
      context: ./App/docker
      dockerfile: php-cli.docker
    environment:
      APP_DEBUG: 1
    volumes:
      - ./App:/app
      - composer:/root/.composer/cache

  postgres:
    image: postgres:16
    ports:
      - ${POSTGRES_PORT}:5432
    container_name: ${POSTGRES_CONTAINER_NAME}
    working_dir: /app
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - dump:/app/dump
      - postgresql:/var/lib/postgresql/data

volumes:
  postgresql:
  composer:
  dump: